hmcts/ccd-elastic-search

- Jenkinsfile_parameterized
> Move to new withParameterizedInfraPipeline

- main.tf
> pointed to curator branch of elk module

- aat.tfvars
- demo.tfvars
- ithc.tfvars
- main.tf
- perftest.tfvars
- prod.tfvars
- sandbox.tfvars
- variables.tf
https://tools.hmcts.net/jira/browse/RDM-6000
Related ELK PR : https://github.com/hmcts/cnp-module-elk/pull/36
Deployed on perftest env:
Green build link : https://build.platform.hmcts.net/blue/organizations/jenkins/HMCTS_CDM%2Fccd-elastic-search/detail/perftest/103/pipeline
> RDM-6000 - ELK change for applications access in AKS

- perftest.tfvars
> add DT oneagent vars for AAT

- main.tf
> add secret and vars from es module

- variables.tf
> update dt vars

- Jenkinsfile_CNP
> Uncomment prod deployment stage

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
- Blocked pipeline to migrate to ccd-shared-infra repo
- Blocked pipeline to migrate to ccd-shared-infra repo
The code needs to be migrated to ccd-shared-infrastructure repository as it is currently affecting that particular pipeline.
For any questions please liaise with RPE Team.
> block pipeline for migration

- Jenkinsfile_CNP
- Jenkinsfile_parameterized
https://tools.hmcts.net/jira/browse/CCD-4050
Fix Jenkins pipeline warnings regarding Groovy after() statements.
**Does this PR introduce a breaking change?**
```
[ ] Yes
[x] No
```
> CCD-4050: Fix Jenkins pipeline warnings

- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-16820
As part of Epic https://tools.hmcts.net/jira/browse/DTSPO-16532 - added additional tags to the ELK CCD VMs
> DTSPO 16820 - Added AUM TAGS to ELK CCD VMs

- .github/renovate.json
- Jenkinsfile_CNP
- README.md
- main.tf
Get pipeline working again
Hasn't been ran in around 2 years
Module has been updated so the correct vnets are being used
Jenkins agent IP ranges have changed since this last ran
> Fix pipeline

- Jenkinsfile_CNP
- main.tf
https://tools.hmcts.net/jira/browse/DTSPO-17634
Upgrade azurerm provider to 3.x
> DTSPO-17634 - AzureRM 3.x upgrade

- demo.tfvars
Increase demo node count to create new vm
> Update demo data node count

- demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17634
Revert to four nodes after deletion of ccd-data-0
> DTSPO-17634 - Revert to 4 data nodes in demo

- main.tf
Use branch on test module to ensure updated template deployment works
> DTSPO-17635 - Use branch on test module

- main.tf
Testing disk SKU change process
Deploying some test resources and planning to shut down the VMs, update the disk SKU, start them up and then merge a change here so the template matches
> DTSPO-17635 - Testing SKU change process

- main.tf
Test VMs have had their disk SKUs changed to standard
Re-enabling my branch so the terraform code reflects this change as well
> DTSPO-17635 - Testing SKU change process - 2

- main.tf
Remove second module call
Process has been tested and it works
Will move onto updating AAT
> DTSPO-17635 - Remove second module

- demo.tfvars
- ithc.tfvars
- main.tf
- perftest.tfvars
- prod.tfvars
Use module branch that allows splitting disks SKUs between osDisk and data didks
> DTSPO-17635 - Use module branch

- demo.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-17668
updating demo environment disk to standard
> DTSPO-17668 - updated demo environment disk to standard

- demo.tfvars
- init.tf
- networking.tf
- new_main.tf
- vm.tf
https://tools.hmcts.net/jira/browse/DTSPO-25565
Deploying demo-int environment to run tests.
Sandbox environment already deployed using same config
> Dtspo 25565 demo int

- lb.tf
- sandbox.tfvars
- variables.tf
https://tools.hmcts.net/jira/browse/DTSPO-25523
Adds a new standard internal load balancer to code base for elastic search.
> Code for standard internal load balancer

- demo.tfvars
- lb.tf
[DTSPO-25523](https://tools.hmcts.net/jira/browse/DTSPO-25523)
build out standard lb for demo-int
> Build lb for demo int

- aat.tfvars
- demo.tfvars
- ithc.tfvars
- main.tf
- perftest.tfvars
- prod.tfvars
https://tools.hmcts.net/jira/browse/DTSPO-25668
Update LB URL IP with variable
> Update LB URL IP with var

- prod_import.tf
See [PROJ-XXXXXX](https://tools.hmcts.net/jira/browse/PROJ-XXXXXX)
**CVE Suppression:** Are there any CVEs present in the codebase (either newly introduced or pre-existing) that are being intentionally suppressed or ignored by this commit?
> adding new imports
